### ISSUE TITLE
Scripto + Metadata Browse throws error on public side

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Scripto#64]
If you have Metadata Browse and Scripto installed, public views of documents or media throws the following error:

```
Omeka\Service\Exception\RuntimeException: Cannot manage settings when no target ID is set. in /var/www/html/omeka-s/application/src/Settings/AbstractTargetSettings.php:97
Stack trace:
#0 /var/www/html/omeka-s/application/src/Settings/AbstractSettings.php(149): Omeka\Settings\AbstractTargetSettings->setCache()
#1 /var/www/html/omeka-s/application/src/Settings/AbstractSettings.php(95): Omeka\Settings\AbstractSettings->cache()
#2 /var/www/html/omeka-s/application/src/Settings/AbstractTargetSettings.php(71): Omeka\Settings\AbstractSettings->get('metadata_browse...', Array)
#3 /var/www/html/omeka-s/modules/MetadataBrowse/Module.php(180): Omeka\Settings\AbstractTargetSettings->get('metadata_browse...', Array)
#4 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): MetadataBrowse\Module->repValueHtml(Object(Zend\EventManager\Event))
#5 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(144): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#6 /var/www/html/omeka-s/application/src/Api/Representation/ValueRepresentation.php(55): Zend\EventManager\EventManager->trigger('rep.value.html', Object(Omeka\Api\Representation\ValueRepresentation), Object(ArrayObject))
#7 /var/www/html/omeka-s/application/view/common/resource-values.phtml(39): Omeka\Api\Representation\ValueRepresentation->asHtml()
#8 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/var/www/html/o...')
#9 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/Helper/Partial.php(61): Zend\View\Renderer\PhpRenderer->render(NULL, Array)
#10 /var/www/html/omeka-s/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(437): Zend\View\Helper\Partial->__invoke('common/resource...', Array)
#11 /var/www/html/omeka-s/modules/Scripto/view/scripto/public-app/media/show.phtml(39): Omeka\Api\Representation\AbstractResourceEntityRepresentation->displayValues()
#12 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/var/www/html/o...')
#13 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#14 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#15 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#16 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#17 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#18 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#19 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#20 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#21 /var/www/html/omeka-s/index.php(21): Zend\Mvc\Application->run()
#22 {main}
```

**Comment by mebrett** [comment]
Some notes: this happens only when the "Use global configuration on admin side" checkbox for metadata browse is Unchecked. Ex http://dev.omeka.org/mebrett/testomekas/scripto/s/scriptosite/1/1/7846/media

**Comment by jimsafley** [comment]
The error will be fixed in the next MetataBrowse release, so closing this issue.
